Static Linux builds with Alpine

diff --git a/.azure/azure-linux-template.yml b/.azure/azure-linux-template.yml
--- a/.azure/azure-linux-template.yml
+++ b/.azure/azure-linux-template.yml
@@ -10,17 +10,31 @@ jobs:
       GHC 8.4:
         BUILD: stack
         STACK_YAML: stack-ghc-84.yaml
+        EXTRA_SUFFIX: ""
+        GHC_OPTIONS: "-Werror"
       GHC 8.6:
         BUILD: stack
         STACK_YAML: stack-ghc-86.yaml
+        EXTRA_SUFFIX: ""
+        GHC_OPTIONS: "-Werror"
       GHC 8.8:
         BUILD: stack
         STACK_YAML: stack-ghc-88.yaml
+        EXTRA_SUFFIX: ""
+        GHC_OPTIONS: "-Werror"
+      Alpine:
+        BUILD: stack
+        STACK_YAML: stack-alpine.yaml
+        EXTRA_SUFFIX: "alpine"
+        ARGS: --system-ghc --no-install-ghc
+        GHC_OPTIONS: "-Werror -optl-static"
       style:
         BUILD: style
+        EXTRA_SUFFIX: ""
       pedantic:
         BUILD: pedantic
         STACK_YAML: stack.yaml
+        EXTRA_SUFFIX: ""
   steps:
   - script: |
       export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
@@ -28,8 +42,8 @@ jobs:
       curl -f -L "https://github.com/fpco/cache-s3/releases/download/${CACHE_S3_VERSION}/cache-s3-${CACHE_S3_VERSION}-${OS_NAME}-x86_64.tar.gz" -o ~/.local/bin/cache-s3.tar.gz
       tar xzf ~/.local/bin/cache-s3.tar.gz -C ~/.local/bin
       export PATH=$HOME/.local/bin:$PATH;
-      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}" restore stack --base-branch="${BASE_BRANCH}"
-      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}" restore stack work --base-branch="${BASE_BRANCH}"
+      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}${EXTRA_SUFFIX}" restore stack --base-branch="${BASE_BRANCH}"
+      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}${EXTRA_SUFFIX}" restore stack work --base-branch="${BASE_BRANCH}"
       etc/scripts/ci-setup.sh
       case "$BUILD" in
         style)
@@ -38,11 +52,9 @@ jobs:
           ;;
         *)
           export PATH=$HOME/.local/bin:$PATH
-          stack --install-ghc $ARGS test --bench --only-dependencies
+          stack $ARGS test --bench --only-dependencies
           ;;
       esac
-      GHC_OPTIONS="-Werror"
-      if [ "$GHCVER" = "8.2.1" ]; then GHC_OPTIONS="$GHC_OPTIONS -Wno-missing-home-modules"; fi
       set -ex
       case "$BUILD" in
         style)
@@ -51,7 +63,16 @@ jobs:
           hlint test/ --cpp-simple
           ;;
         stack)
-          stack test --haddock --no-haddock-deps --ghc-options="$GHC_OPTIONS"
+          stack $ARGS test --haddock --no-haddock-deps --ghc-options="$GHC_OPTIONS" --copy-bins --local-bin-path bin
+
+          # Get output about whether the exe is dynamically linked
+          # Ignore the exit code though, we don't want to fail just because it is static
+          ldd ./bin/stack || true
+
+          # Make sure we can run the executable on this OS
+          # Important to make sure the Alpine exe is properly static
+          ./bin/stack --version
+
           ;;
         pedantic)
           stack --system-ghc build --pedantic
@@ -94,9 +115,9 @@ jobs:
       export AWS_SECRET_ACCESS_KEY="$(AWS_SECRET_ACCESS_KEY)";
       export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
       if [ "$(Build.SourceBranchName)" = "${BASE_BRANCH}" ]; then
-        cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}" save stack;
+        cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}${EXTRA_SUFFIX}" save stack;
       fi;
-      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}" save stack work
+      cache-s3 --prefix="${CACHE_S3_PREFIX}" --git-branch="$(Build.SourceBranchName)" --suffix="${OS_NAME}${EXTRA_SUFFIX}" save stack work
     condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
     env:
       OS_NAME: ${{ parameters.os }}
